import { db } from "./client";
import { trees } from "./schema";

const treesData = [
  {
    name: "Chêne Pédonculé",
    species: "Quercus robur",
    description: "Le chêne pédonculé est l'un des arbres les plus emblématiques de France. Il peut vivre plus de 1000 ans et atteindre 40 mètres de hauteur.",
    localisation: "Europe de l'Ouest",
    co2PerYear: 22,
    o2_prod: 28,           
    price: "29.99",
    imageUrl: "https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?w=800&auto=format&fit=crop",
    stock: 50,
  },
  {
    name: "Érable Sycomore",
    species: "Acer pseudoplatanus",
    description: "L'érable sycomore est un arbre à croissance rapide apprécié pour son feuillage dense et ses graines ailées. Idéal pour les grandes parcelles.",
    localisation: "Europe Centrale",
    co2PerYear: 15,
    o2_prod: 20,
    price: "24.99",
    imageUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&auto=format&fit=crop",
    stock: 35,
  },
  {
    name: "Hêtre Commun",
    species: "Fagus sylvatica",
    description: "Le hêtre commun est un grand arbre forestier au feuillage caduc d'un vert brillant au printemps et doré en automne.",
    localisation: "Europe Tempérée",
    co2PerYear: 18,
    o2_prod: 24,
    price: "34.99",
    imageUrl: "https://images.unsplash.com/photo-1448375240586-882707db888b?w=800&auto=format&fit=crop",
    stock: 20,
  },
  {
    name: "Châtaignier",
    species: "Castanea sativa",
    description: "Le châtaignier est un arbre fruitier majestueux qui produit des châtaignes comestibles. Il peut vivre plusieurs siècles.",
    localisation: "Méditerranée",
    co2PerYear: 20,
    o2_prod: 26,
    price: "27.50",
    imageUrl: "https://images.unsplash.com/photo-1516912481808-3406841bd33c?w=800&auto=format&fit=crop",
    stock: 40,
  },
  {
    name: "Tilleul à Grandes Feuilles",
    species: "Tilia platyphyllos",
    description: "Le tilleul est apprécié pour son ombre généreuse, ses fleurs mellifères très parfumées et ses propriétés médicinales.",
    localisation: "Europe Centrale",
    co2PerYear: 12,
    o2_prod: 16,
    price: "22.00",
    imageUrl: "https://images.unsplash.com/photo-1474511320723-9a56873867b5?w=800&auto=format&fit=crop",
    stock: 60,
  },
  {
    name: "Bouleau Blanc",
    species: "Betula pendula",
    description: "Le bouleau blanc est reconnaissable à son élégante écorce blanche et brillante. Pionnier des milieux ouverts, il pousse rapidement et résiste bien au froid.",
    localisation: "Europe du Nord",
    co2PerYear: 10,
    o2_prod: 13,
    price: "19.99",
    imageUrl: "https://images.unsplash.com/photo-1509316785289-025f5b846b35?w=800&auto=format&fit=crop",
    stock: 75,
  },
  {
    name: "Frêne Commun",
    species: "Fraxinus excelsior",
    description: "Le frêne commun est un grand arbre forestier au bois solide et flexible. Il affectionne les sols humides et les bords de rivières.",
    localisation: "Europe de l'Ouest",
    co2PerYear: 16,
    o2_prod: 21,
    price: "26.00",
    imageUrl: "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?w=800&auto=format&fit=crop",
    stock: 30,
  },
  {
    name: "Orme de Montagne",
    species: "Ulmus glabra",
    description: "L'orme de montagne est un arbre robuste aux grandes feuilles rugueuses. Il pousse dans les forêts de montagne et les versants rocailleux.",
    localisation: "Europe Montagnarde",
    co2PerYear: 14,
    o2_prod: 18,
    price: "31.00",
    imageUrl: "https://images.unsplash.com/photo-1462275646964-a0e3386b89fa?w=800&auto=format&fit=crop",
    stock: 15,
  },
  {
    name: "Pin Sylvestre",
    species: "Pinus sylvestris",
    description: "Le pin sylvestre est l'un des résineux les plus répandus d'Europe. Son tronc rougeâtre et son feuillage persistant bleu-vert en font un arbre très reconnaissable.",
    localisation: "Eurasie",
    co2PerYear: 9,
    o2_prod: 12,
    price: "18.50",
    imageUrl: "https://images.unsplash.com/photo-1425913397330-cf8af2ff40a1?w=800&auto=format&fit=crop",
    stock: 80,
  },
  {
    name: "Sapin Pectiné",
    species: "Abies alba",
    description: "Le sapin pectiné est un conifère majestueux pouvant dépasser 50 mètres. Ses aiguilles planes et ses cônes dressés le distinguent des autres résineux.",
    localisation: "Alpes & Pyrénées",
    co2PerYear: 11,
    o2_prod: 14,
    price: "23.00",
    imageUrl: "https://images.unsplash.com/photo-1483982258113-b72862e6cff6?w=800&auto=format&fit=crop",
    stock: 25,
  },
  {
    name: "Cerisier Sauvage",
    species: "Prunus avium",
    description: "Le merisier ou cerisier sauvage produit de petites cerises noires appréciées des oiseaux. Au printemps, ses fleurs blanches illuminent les forêts.",
    localisation: "Europe & Asie Mineure",
    co2PerYear: 8,
    o2_prod: 11,
    price: "32.00",
    imageUrl: "https://images.unsplash.com/photo-1522093537031-3ee69e6b1746?w=800&auto=format&fit=crop",
    stock: 28,
  },
  {
    name: "Noyer Commun",
    species: "Juglans regia",
    description: "Le noyer commun est un arbre fruitier au port majestueux. Il produit des noix comestibles et son bois est très prisé en ébénisterie.",
    localisation: "Asie Centrale",
    co2PerYear: 25,
    o2_prod: 32,           
    price: "38.00",
    imageUrl: "https://images.unsplash.com/photo-1502082553048-f009c37129b9?w=800&auto=format&fit=crop",
    stock: 18,
  },
  {
    name: "Épicéa Commun",
    species: "Picea abies",
    description: "L'épicéa commun, aussi appelé épicéa de Norvège, est le sapin de Noël traditionnel. Il forme de vastes forêts dans les montagnes d'Europe.",
    localisation: "Europe du Nord",
    co2PerYear: 13,
    o2_prod: 17,
    price: "16.99",
    imageUrl: "https://images.unsplash.com/photo-1511497584788-876760111969?w=800&auto=format&fit=crop",
    stock: 90,
  },
  {
    name: "Aubépine Monogyne",
    species: "Crataegus monogyna",
    description: "L'aubépine est un arbuste épineux couvert de fleurs blanches au printemps et de baies rouges en automne. Elle offre un refuge précieux pour la faune.",
    localisation: "Europe & Maghreb",
    co2PerYear: 5,
    o2_prod: 7,
    price: "14.50",
    imageUrl: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800&auto=format&fit=crop",
    stock: 100,
  },
  {
    name: "Charme Commun",
    species: "Carpinus betulus",
    description: "Le charme commun est un arbre de sous-bois au tronc cannelé très caractéristique. Son feuillage denté vire au jaune doré en automne.",
    localisation: "Europe Tempérée",
    co2PerYear: 11,
    o2_prod: 15,
    price: "21.00",
    imageUrl: "https://images.unsplash.com/photo-1518495973542-4542c06a5843?w=800&auto=format&fit=crop",
    stock: 55,
  },
];

async function seed() {
  await db.delete(trees);
  await db.insert(trees).values(treesData);
  console.log(`✅ Inserted ${treesData.length} trees!`);
  process.exit(0);
}

seed().catch((err) => {
  console.error("❌ Seed failed:", err);
  process.exit(1);
});
